### ISSUE TITLE
Android app crash when select folder or files

### ISSUE THREAD

**Issue by xiqishow** [spieglt/FlyingCarpet#45]
When I tapp the "Select Files/Folder" button, whole app crash and quit.
My system is MUI12.5 with Android 11.
`Process: dev.spiegl.flyingcarpet, PID: 26132
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=*/* (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2081)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
	at android.app.Activity.startActivityForResult(Activity.java:5493)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:860)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:249)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:243)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:175)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at dev.spiegl.flyingcarpet.MainActivity.onCreate$lambda$12(MainActivity.kt:348)
	at dev.spiegl.flyingcarpet.MainActivity.$r8$lambda$x6FHI-1BRbvHz4EHXwmTUWs5OvA(Unknown Source:0)
	at dev.spiegl.flyingcarpet.MainActivity$$ExternalSyntheticLambda13.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7515)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
	at android.view.View.performClickInternal(View.java:7492)
	at android.view.View.access$3600(View.java:847)
	at android.view.View$PerformClick.run(View.java:28742)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8171)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

**Comment by xiqishow** [comment]
Sorry,It`s my fault. I disabled some system settings.

**Comment by spieglt** [comment]
No worries, thanks for letting me know. Can you tell me what system settings you changed? Seems like I may not be handling an error properly.

**Comment by firstrose** [comment]
@xiqishow Could you tell me what is the setting? I am using MIUI too and encounted nearly the same problem.
